### ISSUE TITLE
what callback url are you using?

### ISSUE THREAD

**Issue by morelmiles** [ClubTechPro/techpro.club#107]
**Describe the bug**
This is not a bug. @chilarai  I'd like some help with setting up on local machine. In my github app settings, I'm using http://localhost:8080 as my callback URL but I do not get authenticated. Could you advise on what I should use? 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by chilarai** [comment]
Hi. Please use this

**Github**
GB_CONTRIBUTOR_REDIRECT_URI=http://localhost:8080/contributors/github/callback
GB_PROJECT_REDIRECT_URI=http://localhost:8080/projects/github/callback

**Google**
GO_CONTRIBUTOR_REDIRECT_URI=http://localhost:8080/contributors/google/callback
