### ISSUE TITLE
Enhance Readme

### ISSUE THREAD

**Issue by chilarai** [ClubTechPro/techpro.club#108]
We need to remove clutter from our **Readme.md** file. 

**Requirements**
1. Need to remove the Roadmap section
2. Fix grammatical mistakes, if any

In the future, we will migrate the Roadmap to a better place where managing will be much easier

**Comment by hemantwasthere** [comment]
Hey @chilarai, i would like to work on this issue

**Comment by chilarai** [comment]
@hemantwasthere sure.

**Comment by hemantwasthere** [comment]
Thanks @chilarai for assigning the issue

**Comment by hemantwasthere** [comment]
Hey @chilarai, I have opened a PR please check it out

**Comment by chilarai** [comment]
Closed with PR #110
