### ISSUE TITLE
Golang Installation Documentation

### ISSUE THREAD

**Issue by chilarai** [ClubTechPro/techpro.club#109]
Create Golang installation documentation for Mac, Windows 11 and Ubuntu 22
https://github.com/ClubTechPro/techpro.club/blob/master/documentation/go_installation.md

This document will serve as a refresher for people who wants to begin the project from scratch before reading the project installation guide

**Comment by SaumyaBhushan** [comment]
I would like to work on this. Please assign it to me @chilarai .

**Comment by chilarai** [comment]
Thanks @SaumyaBhushan. Sure

**Comment by SaumyaBhushan** [comment]
@chilarai Created a pull request. Please review

**Comment by chilarai** [comment]
Thabks
