### ISSUE TITLE
Replace "About Us" images in html

### ISSUE THREAD

**Issue by chilarai** [ClubTechPro/techpro.club#113]
Help wanted in replacing the existing 2 images in https://techpro.club/company
Anybody willing to take up the task is most welcome

You will download 2 free images from Unsplash.com and replace the images. Here are the links to images
1. https://unsplash.com/photos/kY2H30v6Bs4
2. https://unsplash.com/photos/Zyx1bK9mqmA

**Comment by Abdirizaks12** [comment]
assign me please.

**Comment by chilarai** [comment]
Sure. I have assigned

**Comment by Abdirizaks12** [comment]
sorry, its my first time it will take time, i know how to fix it.

**Comment by chilarai** [comment]
No problem. Please take your time.

**Comment by yuvi2565** [comment]
@chilarai can I work on this

**Comment by chilarai** [comment]
Hi @yuvi2565, the issue has been already assigned. But you may look into other issues if you want.
Also adding up more issues

**Comment by chilarai** [comment]
Closed with PR #116
