### ISSUE TITLE
Remove .DS_Store file from all folders

### ISSUE THREAD

**Issue by chilarai** [ClubTechPro/techpro.club#114]
Help is needed to remove `.DS_store` files from all the folders and add a rule to `.gitignore` to exclude all the future commits.
If possible, also add rules to exclude all Golang-related temp/unwanted files

**Comment by satyamgupta1495** [comment]
Hey chilarai, would love to work on this issue! could you assign this to me?

**Comment by chilarai** [comment]
Thanks @satyamgupta1495. I have assigned

**Comment by satyamgupta1495** [comment]
Hey Chilarai, Just a quick question to you, do you want me to exclude all the commits in any specific folder or the whole project? 
Also Is it ok if I leave the  " exclude all Golang-related temp/unwanted files" part coz I don't use Golang and I don't wanna mess this up

**Comment by chilarai** [comment]
You may write a rule to ignore all future .DS_Store commits In `.gitignore`. That should be enough

**Comment by chilarai** [comment]
PR #117
