### ISSUE TITLE
CSS issue. GitHub project list card in profiles section is irregular

### ISSUE THREAD

**Issue by chilarai** [ClubTechPro/techpro.club#119]
**Describe the bug**
When viewing the list of personal projects on the profile page, the containing card sizes are not fixed sizes due to which the page looks unprofessional. 

**To Reproduce*
1. Login with Github
2. Click on the `View Profile dropdown from your name on the right top corner
3. Scroll down to GitHub Repositories
4. See the CSS.

**Expected behavior**
The GitHub project cards should be uniform

**Comment by RohitV5** [comment]
@chilarai Please assign this to me.

**Comment by RohitV5** [comment]
@chilarai Please review

**Comment by chilarai** [comment]
Thanks, I will do
