### ISSUE TITLE
Accounts without a profile avatar and name in Github breaks

### ISSUE THREAD

**Issue by chilarai** [ClubTechPro/techpro.club#92]
**Describe the bug**
Those accounts in Github where no profile avatars are set, shows a broken image link.
Also, people without any names on Github, show up some random characters `%!s(<nil>)`

**Comment by RohitV5** [comment]
@chilarai Please assign this to me.

**Comment by chilarai** [comment]
Thanks @RohitV5

**Comment by RohitV5** [comment]
@chilarai Please review.

**Comment by chilarai** [comment]
Thanks Rohit for the PR. I have checked and merged already
