### ISSUE TITLE
Projects link broken from notifications

### ISSUE THREAD

**Issue by chilarai** [ClubTechPro/techpro.club#96]
**Describe the bug**
When navigating to projects details page from notifications, we get 404

**To Reproduce**
1. Login to htjtps://techpro.club
2. Click notifications
3. Click any project link from the notifications page or from the notifications ribbon.
4. See error 404, page not found

**Expected behavior**
It should have landed in `https://techpro.club/projects/view?projectid=<SOME_ID>` instead of  `https://techpro.club/projects/view/<SOME_ID>`

**Comment by RohitV5** [comment]
@chilarai Please assign this to me.

**Comment by chilarai** [comment]
Thanks @RohitV5. I have assigned this to you

**Comment by RohitV5** [comment]
@chilarai Please review
